"""
Synthetic Ground Motion Generation

This module provides functions for generating synthetic earthquake ground
motions and reading seismogram files.
"""

from typing import Optional

import numpy as np
from numpy.typing import NDArray
from scipy import signal


def generate_synthetic_ground_motion(
    duration: float = 30.0,
    dt: float = 0.01,
    target_pga: float = 0.3,
    predominant_freq: float = 2.0,
    bandwidth: float = 1.5,
    seed: Optional[int] = None,
) -> tuple[NDArray[np.floating], NDArray[np.floating]]:
    """
    Generate synthetic earthquake ground motion using modulated filtered noise.

    The ground motion is generated by:
    1. Creating band-limited white noise
    2. Applying an envelope function (Saragoni-Hart type)
    3. Scaling to target PGA

    Parameters
    ----------
    duration : float
        Total duration in seconds.
    dt : float
        Time step in seconds.
    target_pga : float
        Target peak ground acceleration in g.
    predominant_freq : float
        Predominant frequency of the motion in Hz.
    bandwidth : float
        Bandwidth parameter for the frequency content.
    seed : int, optional
        Random seed for reproducibility.

    Returns
    -------
    time : ndarray
        Time vector in seconds.
    acceleration : ndarray
        Ground acceleration time history in g.
    """
    if seed is not None:
        np.random.seed(seed)

    # Time vector
    n_points = int(duration / dt) + 1
    time = np.linspace(0, duration, n_points)

    # Generate white noise
    noise = np.random.randn(n_points)

    # Design bandpass filter around predominant frequency
    nyquist = 0.5 / dt
    low_freq = max(0.1, predominant_freq - bandwidth)
    high_freq = min(nyquist - 0.1, predominant_freq + bandwidth)

    # Normalize frequencies for filter design
    low_norm = low_freq / nyquist
    high_norm = high_freq / nyquist

    # Ensure valid filter frequencies
    low_norm = max(0.01, min(low_norm, 0.99))
    high_norm = max(low_norm + 0.01, min(high_norm, 0.99))

    # Butterworth bandpass filter
    b, a = signal.butter(4, [low_norm, high_norm], btype="band")
    filtered_noise = signal.filtfilt(b, a, noise)

    # Apply Saragoni-Hart envelope
    # e(t) = a * t^b * exp(-c*t)
    # Parameters chosen for realistic earthquake envelope
    t_max = duration * 0.3  # Time of maximum amplitude
    b_env = 2.0
    c_env = b_env / t_max

    # Avoid division by zero at t=0
    envelope = np.zeros_like(time)
    nonzero_mask = time > 0
    envelope[nonzero_mask] = (time[nonzero_mask] ** b_env) * np.exp(-c_env * time[nonzero_mask])

    # Normalize envelope to have maximum of 1
    if np.max(envelope) > 0:
        envelope = envelope / np.max(envelope)

    # Apply envelope to filtered noise
    acceleration = filtered_noise * envelope

    # Scale to target PGA
    current_pga = np.max(np.abs(acceleration))
    if current_pga > 0:
        acceleration = acceleration * (target_pga / current_pga)

    return time, acceleration


def generate_harmonic_ground_motion(
    duration: float = 20.0,
    dt: float = 0.01,
    amplitude: float = 0.1,
    frequency: float = 1.0,
    n_cycles: Optional[int] = None,
) -> tuple[NDArray[np.floating], NDArray[np.floating]]:
    """
    Generate harmonic ground motion for testing purposes.

    Parameters
    ----------
    duration : float
        Total duration in seconds.
    dt : float
        Time step in seconds.
    amplitude : float
        Amplitude in g.
    frequency : float
        Frequency in Hz.
    n_cycles : int, optional
        Number of cycles. If provided, overrides duration.

    Returns
    -------
    time : ndarray
        Time vector in seconds.
    acceleration : ndarray
        Ground acceleration time history in g.
    """
    if n_cycles is not None:
        duration = n_cycles / frequency

    n_points = int(duration / dt) + 1
    time = np.linspace(0, duration, n_points)

    # Sinusoidal motion with ramp-up and ramp-down
    ramp_time = min(2.0, duration * 0.1)
    ramp_points = int(ramp_time / dt)

    acceleration = amplitude * np.sin(2 * np.pi * frequency * time)

    # Apply ramp-up
    if ramp_points > 0:
        ramp_up = np.linspace(0, 1, ramp_points)
        acceleration[:ramp_points] *= ramp_up

        # Apply ramp-down
        ramp_down = np.linspace(1, 0, ramp_points)
        acceleration[-ramp_points:] *= ramp_down

    return time, acceleration


def read_bbp_seismogram(filepath: str) -> tuple[NDArray[np.floating], NDArray[np.floating]]:
    """
    Read a Broadband Platform (BBP) format seismogram file.

    This is a placeholder implementation. BBP files typically have
    a header followed by time and acceleration columns.

    Parameters
    ----------
    filepath : str
        Path to the BBP seismogram file.

    Returns
    -------
    time : ndarray
        Time vector in seconds.
    acceleration : ndarray
        Ground acceleration time history in g or cm/s^2.

    Raises
    ------
    NotImplementedError
        Full BBP parsing is not yet implemented.
    FileNotFoundError
        If the file does not exist.
    """
    # Placeholder: attempt to read as simple two-column format
    try:
        data = np.loadtxt(filepath, comments="#")
        if data.ndim == 1:
            raise ValueError("Expected two-column data (time, acceleration)")
        time = data[:, 0]
        acceleration = data[:, 1]
        return time, acceleration
    except Exception as e:
        raise NotImplementedError(
            f"BBP file parsing not fully implemented. Error: {e}\n"
            "Expected simple two-column format (time, acceleration)."
        ) from e


def baseline_correction(
    acceleration: NDArray[np.floating],
    dt: float,
    order: int = 3,
) -> NDArray[np.floating]:
    """
    Apply polynomial baseline correction to ground motion.

    Parameters
    ----------
    acceleration : ndarray
        Acceleration time history.
    dt : float
        Time step in seconds.
    order : int
        Order of polynomial to fit and remove.

    Returns
    -------
    ndarray
        Baseline-corrected acceleration.
    """
    n_points = len(acceleration)
    time = np.arange(n_points) * dt

    # Fit polynomial to the acceleration
    coeffs = np.polyfit(time, acceleration, order)
    baseline = np.polyval(coeffs, time)

    return acceleration - baseline


def apply_highpass_filter(
    acceleration: NDArray[np.floating],
    dt: float,
    cutoff_freq: float = 0.1,
    order: int = 4,
) -> NDArray[np.floating]:
    """
    Apply highpass filter to remove low-frequency drift.

    Parameters
    ----------
    acceleration : ndarray
        Acceleration time history.
    dt : float
        Time step in seconds.
    cutoff_freq : float
        Cutoff frequency in Hz.
    order : int
        Filter order.

    Returns
    -------
    ndarray
        Filtered acceleration.
    """
    nyquist = 0.5 / dt
    normalized_cutoff = cutoff_freq / nyquist

    if normalized_cutoff >= 1.0:
        raise ValueError(
            f"Cutoff frequency ({cutoff_freq} Hz) must be less than "
            f"Nyquist frequency ({nyquist} Hz)"
        )

    b, a = signal.butter(order, normalized_cutoff, btype="high")
    return signal.filtfilt(b, a, acceleration)


def compute_response_spectrum(
    time: NDArray[np.floating],
    acceleration: NDArray[np.floating],
    periods: Optional[NDArray[np.floating]] = None,
    damping_ratio: float = 0.05,
) -> tuple[NDArray[np.floating], NDArray[np.floating]]:
    """
    Compute pseudo-acceleration response spectrum.

    Parameters
    ----------
    time : ndarray
        Time vector in seconds.
    acceleration : ndarray
        Ground acceleration in g.
    periods : ndarray, optional
        Periods at which to compute spectral values.
    damping_ratio : float
        Damping ratio for SDOF oscillators.

    Returns
    -------
    periods : ndarray
        Natural periods in seconds.
    Sa : ndarray
        Spectral acceleration in g.
    """
    if periods is None:
        periods = np.logspace(-2, 1, 100)  # 0.01 to 10 seconds

    dt = time[1] - time[0]
    acc_mps2 = acceleration * 9.81  # Convert g to m/s^2

    Sa = np.zeros(len(periods))

    for i, T in enumerate(periods):
        if T < 2 * dt:
            # For very short periods, use PGA
            Sa[i] = np.max(np.abs(acceleration))
            continue

        omega = 2 * np.pi / T
        omega_d = omega * np.sqrt(1 - damping_ratio**2)

        # SDOF response using Duhamel integral (simplified)
        # This is a simplified implementation; more accurate methods exist
        u = np.zeros(len(time))
        v = np.zeros(len(time))

        exp_factor = np.exp(-damping_ratio * omega * dt)
        sin_factor = np.sin(omega_d * dt)
        cos_factor = np.cos(omega_d * dt)

        A = exp_factor * (cos_factor + damping_ratio / np.sqrt(1 - damping_ratio**2) * sin_factor)
        B = exp_factor * sin_factor / omega_d

        for j in range(1, len(time)):
            u[j] = A * u[j - 1] + B * v[j - 1] - dt * acc_mps2[j - 1] / omega**2
            v[j] = -(omega**2) * B * u[j - 1] + A * v[j - 1]

        # Spectral acceleration (pseudo-acceleration)
        Sa[i] = np.max(np.abs(u)) * omega**2 / 9.81

    return periods, Sa
